<?php
/**
 * @file
 * mBootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

/**
 * Implements hook_preprocess_user().
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function mybootstrap_theme_suggestions_form_alter(array &$suggestions, array $variables) {
    if ($variables['element']['#form_id'] == 'view-filters') {
        $suggestions[] = 'form__actu_block_form';
    }
}
