api_key: 82416246771cb31060c50b2beb48d5be-us15
cron: false
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
_core:
  default_config_hash: x8k6uOqmSHPqpp71jYGxHF3_SAs3U-Pha3YCntQIhPU
