site_key: 6LeV9hcUAAAAAETQRbZb40AWJgTDzW4m5ddIshnq
secret_key: 6LeV9hcUAAAAAMnXqXk1lh27I1CrnqqLEVzPxI5_
widget:
  theme: dark
  type: image
  size: ''
  tabindex: 0
  noscript: false
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
