site_key: 6LdSTBcUAAAAAJyadpajEvl8sTMC8xnELSyOyRwW
secret_key: 6LdSTBcUAAAAAAQumoJ5pjT71xWUbl0zJrJS-zkz
widget:
  theme: dark
  type: image
  size: ''
  tabindex: 0
  noscript: false
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
