<?php

/**
 * @file
 * Contains account.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_help().
 */
function account_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the account module.
    case 'help.page.account':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Account') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function account_theme() {
  return [
    'account' => [
      'template' => 'account',
      'render element' => 'children',
        'variables' => [
            'nom' => '',
            'prenom'=>'',
            'userid'=>'',
            'picture'=>'',
            'path' =>''
        ],
    ],
  ];
}


function account_user_insert($account) {

    $type = $account->get('field_type_d_utilisateur')->getString();


    if($type == 'Journaliste')
    {
        $account->addRole('journaliste');
        $account->save();
    }

}

function account_form_alter(&$form, &$form_state, $form_id){



}

